name: BB Session
on:
  push:
    branches:
      - master
jobs:
upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: .
          container_name: $web
          connection_string: ${{ secrets.ConnectionString }}